sudo: false
dist: trusty
language: node_js

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

node_js:
  - "6"

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - npm install -g npm
  - npm install

before_script:
  - nohup npm run webdriver > webdriver.log &
  - nohup npm run express > express.log &
  - sleep 10

script:
  - npm test
  - npm run e2e
  - npm run protractor

after_success:
  - npm run coverage
  - npm run coverage:upload
  - npm run semantic-release
