sudo: false
language: node_js
node_js:
  - "5"
  - "4"

cache:
  directories:
    - node_modules

env:
  global:
    secure: Iudzt3u8W/JujxrD9U+Z23rg3IS6mE604C/u49yvs+/8t+MwMfc1XHorIc5tHy+Uo5ViXc1sa/teRcsVFnZ5X+GzHV0Fd3TlbDRKopT4stHrRaApw1SJxUgJMMpGKU5jQnPo4E4VeDnU7tuylmX8N8rFudHg313yKi4CJsnphwQ=

addons:
  firefox: "latest"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install -g npm@2
  - npm install

before_script:
  - ./node_modules/.bin/webdriber-manager update --standalone
  - ./node_modules/.bin/webdriver-manager start > /dev/null &
  - sleep 2
  - npm start > /dev/null &
  - sleep 2

script:
  - npm run e2e
  - npm run coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
