sudo: false
language: node_js

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

node_js:
  - "6"
  - "4"

addons:
  firefox: "latest"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install -g webdriver-manager
  - npm install

before_script:
  - webdriver-manager update
  - nohup webdriver-manager start 2>&1 &
  - nohup npm start 2>&1 &
  - sleep 5

script:
  - npm test
  - npm run e2e
  - npm run protractor

after_success:
  - npm run coverage
  - npm run coverage:upload
  - npm run semantic-release
