sudo: false
language: node_js

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

node_js:
  - "5"
  - "4"

addons:
  firefox: "latest"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm i -g npm@2
  - npm i -g webdriver-manager@10.0.1
  - npm i

before_script:
  - webdriver-manager update
  - webdriver-manager start > /dev/null &
  - npm start > /dev/null &
  - sleep 5

script:
  - npm test
  - npm run e2e

after_success:
  - npm run coverage
  - npm run coverage:upload
  - npm run semantic-release
