sudo: required
dist: trusty
language: node_js
node_js: "8"

notifications:
  email: false

cache:
  directories:
    - node_modules

install:
  - npm install -g npm
  - npm install

before_script:
  - nohup npm run express > express.log &
  - sleep 2

script:
  - npm test

after_success:
  - npm run coverage
  - npx semantic-release
