language: node_js
node_js:
  - '0.10'

env:
  global:
    secure: Iudzt3u8W/JujxrD9U+Z23rg3IS6mE604C/u49yvs+/8t+MwMfc1XHorIc5tHy+Uo5ViXc1sa/teRcsVFnZ5X+GzHV0Fd3TlbDRKopT4stHrRaApw1SJxUgJMMpGKU5jQnPo4E4VeDnU7tuylmX8N8rFudHg313yKi4CJsnphwQ=

cache:
  directories:
    - node_modules

install:
  - npm install -g codeclimate-test-reporter
  - npm install -g coveralls
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - phantomjs -w > /dev/null &
  - sleep 3
  - npm start &
  - sleep 3

script: npm run coverage

after_script:
  - cat ./coverage/lcov.info | coveralls
  - codeclimate < ./coverage/lcov.info
